package de.heckenmann.visualagent.agent.tools

import de.heckenmann.visualagent.agent.ToolDefinition
import de.heckenmann.visualagent.agent.ToolId
import de.heckenmann.visualagent.agent.ToolResult

/**
 * Application-level tool that can be exposed to an LLM through Spring AI.
 */
interface VisualAgentTool {
    /**
     * Provider-neutral tool definition.
     */
    val definition: ToolDefinition

    /**
     * Execute this tool using JSON input generated by the model.
     *
     * @param inputJson JSON argument object passed by Spring AI
     * @param context Request-scoped execution metadata
     * @return Structured tool result
     */
    fun execute(inputJson: String, context: Map<String, Any> = emptyMap()): ToolResult
}

/**
 * Convert an application tool ID into a provider-safe function name.
 *
 * @return Name that can be used as a Spring AI function callback name
 */
fun ToolId.toFunctionName(): String = value.replace(Regex("[^A-Za-z0-9_]"), "_")

