#Visual Agent Configuration
#Sun May 31 15:29:33 CEST 2026
browser.default=firefox
database.path=./data/visual-agent.db
ollama.local.url=http\://localhost\:11434
ollama.model=gemma4\:e2b
ui.font.size=14
ui.theme=Nord Dark
