#Visual Agent Configuration
#Fri May 29 17:42:23 CEST 2026
browser.default=firefox
database.path=./data/visual-agent.db
ollama.local.url=http\://localhost\:11434
ollama.model=llama3.2\:3b
ui.font.size=14
ui.theme=Nord Light
