package de.heckenmann.visualagent.agent.tools

import de.heckenmann.visualagent.agent.tools.api.ToolDefinition
import de.heckenmann.visualagent.agent.tools.api.ToolId
import de.heckenmann.visualagent.agent.tools.api.ToolResult
import reactor.core.publisher.Mono

/**
 * Application-level tool that can be exposed to an LLM through Spring AI.
 */
interface VisualAgentTool {
    /**
     * Provider-neutral tool definition.
     */
    val definition: ToolDefinition

    /**
     * Whether this tool manages asynchronous execution and waiting internally.
     *
     * Managed tools retain ownership of their internal scheduling while the registry still
     * applies its reactive timeout and cancellation boundary.
     */
    val managesExecution: Boolean
        get() = false

    /**
     * Execute this tool using JSON input generated by the model.
     *
     * @param inputJson JSON argument object passed by Spring AI
     * @param context Request-scoped execution metadata
     * @return Structured tool result
     */
    fun execute(
        inputJson: String,
        context: Map<String, Any> = emptyMap(),
    ): ToolResult

    /**
     * Execute this tool through its reactive server-side contract.
     *
     * Synchronous tools inherit a deferred [Mono] wrapper. Implementations that already own a
     * non-blocking source can override this method to preserve it. The registry selects the
     * scheduler for synchronous work, timeout handling, and cancellation.
     *
     * @param inputJson JSON argument object passed by Spring AI
     * @param context Request-scoped execution metadata
     * @return Deferred tool result
     */
    fun executeReactive(
        inputJson: String,
        context: Map<String, Any> = emptyMap(),
    ): Mono<ToolResult> = Mono.fromCallable { execute(inputJson, context) }
}

/**
 * Converts an internal tool ID into the sole model-callable provider function name.
 *
 * Internal IDs remain stable for configuration, persistence, and UI display. Provider function
 * names use lower snake case so every provider receives the same portable function contract.
 *
 * @return Lower snake-case name that can be used as a Spring AI function callback name
 * @throws IllegalArgumentException when this ID cannot produce a portable provider function name
 */
fun ToolId.toFunctionName(): String {
    val functionName = value.lowercase().replace(UNSAFE_FUNCTION_NAME_CHARACTERS, "_").trim('_')
    require(PROVIDER_FUNCTION_NAME.matches(functionName)) {
        "Tool ID '$value' cannot produce a valid provider function name."
    }
    return functionName
}

private val UNSAFE_FUNCTION_NAME_CHARACTERS = Regex("[^a-z0-9]+")
private val PROVIDER_FUNCTION_NAME = Regex("[a-z][a-z0-9_]{0,63}")
