CREATE TABLE IF NOT EXISTS long_term_memory (
    id VARCHAR(255) PRIMARY KEY,
    content CLOB NOT NULL,
    embedding BLOB,
    tags VARCHAR(10000),
    created_at VARCHAR(64) DEFAULT '1970-01-01T00:00:00Z',
    access_count INTEGER DEFAULT 0,
    last_accessed VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS project_knowledge (
    id VARCHAR(255) PRIMARY KEY,
    project_path VARCHAR(4096) NOT NULL UNIQUE,
    name VARCHAR(255),
    description CLOB,
    summary CLOB,
    last_accessed VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS user_preferences (
    preference_key VARCHAR(512) PRIMARY KEY,
    preference_value VARCHAR(1000000) NOT NULL,
    preference_type VARCHAR(64) NOT NULL DEFAULT 'string',
    updated_at VARCHAR(64) DEFAULT '1970-01-01T00:00:00Z'
);

CREATE TABLE IF NOT EXISTS conversation_history (
    id VARCHAR(255) PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    role VARCHAR(64) NOT NULL,
    content CLOB NOT NULL,
    metadata CLOB,
    created_at VARCHAR(64) DEFAULT '1970-01-01T00:00:00Z',
    timeline_sequence BIGINT NOT NULL DEFAULT 0,
    context_policy VARCHAR(64) NOT NULL DEFAULT 'SUMMARY_SOURCE'
);

CREATE INDEX IF NOT EXISTS idx_conversation_history_session_created
    ON conversation_history (session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversation_history_timeline_sequence
    ON conversation_history (timeline_sequence DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_conversation_history_context
    ON conversation_history (session_id, context_policy, timeline_sequence DESC);

CREATE TABLE IF NOT EXISTS todos (
    id VARCHAR(255) PRIMARY KEY,
    description CLOB NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'PENDING',
    position INTEGER NOT NULL DEFAULT 0,
    assigned_agent_id VARCHAR(255),
    created_at VARCHAR(64) DEFAULT '1970-01-01T00:00:00Z',
    updated_at VARCHAR(64),
    timeline_sequence BIGINT NOT NULL DEFAULT 0,
    completed_at VARCHAR(64),
    due_date VARCHAR(64),
    terminal_detail CLOB
);
CREATE INDEX IF NOT EXISTS idx_todos_timeline_sequence ON todos (timeline_sequence DESC, id DESC);

CREATE TABLE IF NOT EXISTS deleted_todos (
    id VARCHAR(255) PRIMARY KEY,
    description CLOB NOT NULL,
    status VARCHAR(64) NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    assigned_agent_id VARCHAR(255),
    created_at VARCHAR(64) NOT NULL,
    updated_at VARCHAR(64) NOT NULL,
    timeline_sequence BIGINT NOT NULL DEFAULT 0,
    completed_at VARCHAR(64),
    due_date VARCHAR(64),
    terminal_detail CLOB
);
CREATE INDEX IF NOT EXISTS idx_deleted_todos_updated ON deleted_todos (updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_deleted_todos_timeline_sequence ON deleted_todos (timeline_sequence DESC, id DESC);

CREATE TABLE IF NOT EXISTS conversation_timeline_sequence (
    sequence_value BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS sub_agents (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    status VARCHAR(64) DEFAULT 'IDLE',
    current_task CLOB,
    parent_agent_id VARCHAR(255),
    config CLOB NOT NULL DEFAULT '{"timeout":60,"maxRetries":3,"memoryLimitMb":512}',
    created_at VARCHAR(64) DEFAULT '1970-01-01T00:00:00Z',
    updated_at VARCHAR(64) DEFAULT '1970-01-01T00:00:00Z'
);

CREATE TABLE IF NOT EXISTS sub_agent_configs (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description CLOB NOT NULL,
    model VARCHAR(255) NOT NULL,
    system_prompt CLOB NOT NULL DEFAULT '',
    tools CLOB NOT NULL DEFAULT '[]',
    max_turns INTEGER NOT NULL DEFAULT 5,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at VARCHAR(64) DEFAULT '1970-01-01T00:00:00Z'
);

CREATE TABLE IF NOT EXISTS workspace_files (
    id VARCHAR(255) PRIMARY KEY,
    relative_path VARCHAR(4096) NOT NULL UNIQUE,
    original_name VARCHAR(1024) NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    extracted_text CLOB,
    imported_at VARCHAR(64) DEFAULT '1970-01-01T00:00:00Z',
    updated_at VARCHAR(64) DEFAULT '1970-01-01T00:00:00Z'
);
CREATE INDEX IF NOT EXISTS idx_workspace_files_imported ON workspace_files (imported_at DESC);

CREATE TABLE IF NOT EXISTS skills (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content CLOB NOT NULL,
    content_fingerprint VARCHAR(64) NOT NULL UNIQUE,
    created_at VARCHAR(64) NOT NULL,
    updated_at VARCHAR(64) NOT NULL,
    revision BIGINT NOT NULL DEFAULT 1,
    read_count BIGINT NOT NULL DEFAULT 0,
    last_read_at VARCHAR(64)
);
CREATE INDEX IF NOT EXISTS idx_skills_updated_at ON skills (updated_at DESC, id ASC);

CREATE TABLE IF NOT EXISTS deleted_skill_audit (
    skill_id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    revision BIGINT NOT NULL,
    deleted_at VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS directory_grants (
    id VARCHAR(255) PRIMARY KEY,
    display_name VARCHAR(255) NOT NULL,
    canonical_root VARCHAR(4096) UNIQUE,
    origin VARCHAR(32) NOT NULL,
    mode VARCHAR(32) NOT NULL,
    owner_client_id VARCHAR(255),
    created_at VARCHAR(64) NOT NULL,
    updated_at VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS main_agent_long_term_memory (
    scope VARCHAR(255) PRIMARY KEY,
    content CLOB NOT NULL,
    content_length INTEGER NOT NULL,
    revision BIGINT NOT NULL,
    updated_at VARCHAR(64) NOT NULL
);

INSERT INTO main_agent_long_term_memory (scope, content, content_length, revision, updated_at)
SELECT 'main', '', 0, 0, '1970-01-01T00:00:00Z'
WHERE NOT EXISTS (SELECT 1 FROM main_agent_long_term_memory WHERE scope = 'main');

INSERT INTO user_preferences (preference_key, preference_value, preference_type, updated_at)
SELECT
    'ui.onboarding.v1',
    CASE
        WHEN EXISTS (SELECT 1 FROM conversation_history)
          OR EXISTS (SELECT 1 FROM todos)
          OR EXISTS (SELECT 1 FROM sub_agents)
          OR EXISTS (SELECT 1 FROM workspace_files)
          OR EXISTS (SELECT 1 FROM skills)
        THEN 'COMPLETED'
        ELSE 'NOT_STARTED'
    END,
    'string',
    '1970-01-01T00:00:00Z'
WHERE NOT EXISTS (
    SELECT 1 FROM user_preferences WHERE preference_key = 'ui.onboarding.v1'
);
