package de.heckenmann.visualagent.agent.conversation

/**
 * Result of composing a post-reset welcome message.
 */
sealed class WelcomeResult {
    /**
     * A welcome message generated by the configured provider.
     *
     * @property message The generated greeting text
     */
    data class Generated(
        val message: String,
    ) : WelcomeResult()

    /**
     * A static fallback greeting used because provider generation failed.
     *
     * @property message The fallback greeting text
     * @property error The original provider error for UI reporting
     */
    data class Fallback(
        val message: String,
        val error: Throwable,
    ) : WelcomeResult()
}
